services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cmpc_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
